src/main/resources/wa-task-types-sptribs.dmn
=> WA Configuration - Added defib=ned task types

scripts/camunda-deployment.sh, src/main/resources/wa-task-cancellation-sptribs.dmn, src/main/resources/wa-task-configuration-sptribs.dmn
Task Configuration (added details)
```
[ ] Yes
[ ] No
```
=> Task Cancellation (create file)

src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn
=> Changes for ST-1279

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
Update DMN files (initiation, permissions, configuration)
and Unit test for WA - Admin Task - 'Process listing directions'
```
[ ] Yes
[x] No
```
=> ST-1282-WA - Admin Task - 'Process listing directions'

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
Update DMN files (initiation, permissions, configuration)
and Unit test for WA - Admin Task - Process directions re. listed case
```
[ ] Yes
[x] No
```
=> ST-1284 WA - Admin Task - 'Process directions re. listed case'

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java
=> ST-1276 Admin task process direction returned

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
=> ST-1277 Admin task "process time extension direction returned"

src/main/resources/wa-task-cancellation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/utils/CancellationScenarioBuilder.java
=> ST-1295 Admin task "process resinstatement decision notice"

src/main/resources/wa-task-cancellation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
=> ST-1338 Admin task "process other directions returned"

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
Update DMN files (initiation, permissions, configuration)
and Unit test for WA - Admin Task - 'Process Written Reasons'
```
[ ] Yes
[ ] No
```
=> ST-1294 WA - Admin Task - 'Process Written Reasons'

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
ST-1281-wa-admin-task-process-stay-directions
update 5 dmn and corresponded unit test
```
[ ] Yes
[ x ] No
```
=> added unit test for update DMN

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java
Correcting caseworker-send-order Event ID from sendOrder to caseworker-send-order
Confirmed with Fergal 
```
[ ] Yes
[x] No
```
=> Correcting caseworker-send-order Event ID from sendOrder to caseworker-send-order

src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java
ST-1338-wa-admin-task-process-other-directions-returned
updated task initiation dmn ( fixed spelling mistake ) 
fixed unit test spelling mistake 
```
[ ] Yes
[x] No
```
=> DMN updated and added unit test for update DMN

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
Updating DMN and Unit test for WA - Admin Task - Issue Decision Notice
```
[ ] Yes
[x] No
```
=> ST-1291 WA - Admin Task - Issue Decision Notice

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
Updating DMN and Unit test for WA - Admin Task - Complete Hearing Outcome
```
[ ] Yes
[x] No
```
=> ST-1290 WA - Admin Task - Complete Hearing Outcome

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
Updating DMN and Unit test for WA - Admin Task - Refer Case
```
[ ] Yes
[x] No
```
=> ST-1275 WA - Admin Task - Refer Case

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
…ase and provide directions - Legal Officer
Updating DMN and Unit test for WA - Legal Officer Task - Review new case and provide directions - Legal Officer
```
[ ] Yes
[x] No
```
=> ST-1311 WA - Legal Officer Task - Review new case and provide directions - Legal Officer

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
Updating DMN and Unit test for WA - Legal Officer Task - Review Time extension request - Legal Officer
```
[ ] Yes
[x] No
```
=> ST-1312 WA - Legal Officer Task - Review Time extension request - Legal Officer

src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
Correction for Role name
```
[ ] Yes
[x] No
```
=> ST-1311 Correction for Role name

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
DMN and Unit test for WA - Legal Officer Task - Review stay request - Legal Officer
```
[ ] Yes
[x] No
```
=> ST-1316  WA - Legal Officer Task - Review stay request -  Legal Officer

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
DMN and Unit test for WA - Legal Officer Task - Review listing directions - Legal Officer
```
[ ] Yes
[x] No
```
=> ST-1317 WA - Legal Officer Task - Review listing directions - Legal Officer

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
DMN and Unit test for WA - Legal Officer Task - Review List Case - Legal Officer
```
[ ] Yes
[x] No
```
=> ST-1318-WA - Legal Officer Task - Review List Case - Legal Officer

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
DMN and Unit test for WA - Admin Task - Vet New Case Documents
```
[ ] Yes
[x] No
```
=> ST-1274 WA - Admin Task - Vet New Case Documents

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
DMN and Unit test for WA - Legal Officer Task - Review other request - Legal Officer
```
[ ] Yes
[x] No
```
=> ST-1340- WA - Legal Officer Task - Review other request - Legal Officer

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
ST-1319 WA - Legal Officer Task - 'Review list case (within 5 days) - Legal Officer'
ST-1320 WA - Legal Officer Task - 'Review Postponement request - Legal Officer' 
ST-1321 WA - Legal Officer Task - 'Review Reinstatement request - Legal Officer'
https://tools.hmcts.net/jira/browse/ST-1319
https://tools.hmcts.net/jira/browse/ST-1320
https://tools.hmcts.net/jira/browse/ST-1321
modified DMN file and test
```
[ ] Yes
[x ] No
```
=> ST-1319-1320-1321-WA-legal-officer_task_review

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
ST-1306- WA - Judicial Task - Review Postponement request - Judge DMN And Unit test
```
[ ] Yes
[x] No
```
=> ST-1306- WA - Judicial Task - Review Postponement request - Judge

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
WA - Judicial Task - Review Corrections request - DMN And Unit test
```
[ ] Yes
[x] No
```
=> ST-1307- WA - Judicial Task - Review Corrections request 

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
DMN and Unit test for WA - Judicial Task -Review Written Reasons request
```
[ ] Yes
[x] No
```
=> ST-1309- WA - Judicial Task -Review Written Reasons request

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
DMN and Unit test for WA - Judicial Task - Review Reinstatement request - Judge
```
[ ] Yes
[x] No
```
=> ST-1310 WA - Judicial Task - Review Reinstatement request - Judge

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/ST-1308
DMNs and unit tests  for wa judicial task review set aside request
```
[ ] Yes
[x] No
```
=> ST-1308 DMNs and unit tests  for wa judicial task review set aside request

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
=> ST-1302 Judicial Task - Review stay request Judge

src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
DMN and Unit test required Changes
```
[ ] Yes
[x] No
```
=> ST-1558-DMN and Unit test required Changes

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
DMN and Unit test for WA - Judicial Task - Review other request - Judge
```
[ ] Yes
[x] No
```
=> ST-1339-WA - Judicial Task - Review other request - Judge

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
DMN and Unit test for WA - Judicial Task - Review withdrawal request - Judge
```
[ ] Yes
[x] No
```
=> ST-1299- WA - Judicial Task - Review withdrawal request - Judge

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
DMN and Unit test for WA - Judicial Task - Review Rule 27 request - Judge
```
[ ] Yes
[x] No
```
=> ST-1301 WA - Judicial Task - Review Rule 27 request - Judge

src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/utils/ConfigurationExpectationBuilder.java
DMN and Unit test for WA - Specific Access Request
```
[ ] Yes
[x] No
```
=> ST-1252 WA - Specific Access Request

src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
=> ST-1568 remove Manage Permissions

config/checkstyle/checkstyle.xml, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/DmnDecisionTable.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/ST-1652
resolve auto completable tasks in dmn
```
[ ] Yes
[ ] No
```
=> resolve auto completable tasks in dmn

src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java
Updating a state for referCase and vetNewCaseDocuments event
```
[ ] Yes
[x] No
```
=> Updating a state for referCase and vetNewCaseDocuments event

src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java
Updating a state for vetNewCaseDocuments event
```
[ ] Yes
[x] No
```
=> ST-1655 Updating a state for vetNewCaseDocuments event

src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java
=> Updating DssSubmitted state for vetNewCaseDocuments event

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
DMN and Unit test for WA - Admin Task - Follow up none compliance of directions
```
[ ] Yes
[x] No
```
=> ST-1328 WA - Admin Task - Follow up none compliance of directions

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/utils/ConfigurationExpectationBuilder.java
Adding location name, Case name, Case category etc in DMN. 
```
[ ] Yes
[x] No
```
=> ST-1322-DMN changes

src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/utils/ConfigurationExpectationBuilder.java
Adding casename,caselocation etc
```
[ ] Yes
[x] No
```
=> DMN changes

src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/utils/ConfigurationExpectationBuilder.java
Having due date issue it was working fine before so removing the added config
```
[ ] Yes
[x] No
```
=> Fixing due date issue

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/DTSSTCI-406
Fixed typo
```
[ ] Yes
[x] No
```
=> DTSSTCI-406: Fixed Noncompliance typo

src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn
https://tools.hmcts.net/jira/browse/DTSSTCI-424
Fixed
```
[ ] Yes
[x] No
```
=> DTSSTCI-424: Fixed task name for task processCorrections

src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn
https://tools.hmcts.net/jira/browse/DTSSTCI-436
Changed ‘senior-legal-caseworker’ to ‘senior-tribunal-caseworker’
```
[ ] Yes
[x] No
```
=> DTSSTCI-436: Update senior caseworker role in Permissions DMN

src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn
https://tools.hmcts.net/jira/browse/DTSSTCI-441
removed
```
[ ] Yes
[x] No
```
=> DTSSTCI-441: Removed fee-paid-judge permission from DMN

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-types-st_cic-criminalinjuriescompensation.dmn
https://tools.hmcts.net/jira/browse/DTSSTCI-415
Added
```
[ ] Yes
[x] No
```
=> DTSSTCI-415: Added new tasks to DMN

src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn
https://tools.hmcts.net/jira/browse/DTSSTCI-426
Updated permission DMN
```
[ ] Yes
[x] No
```
=> DTSSTCI-426: Updated permission DMN

src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/DTSSTCI-419
updated
```
[ ] Yes
[x] No
```
=> DTSSTCI-419: Updated task configuration DMN

src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn
https://tools.hmcts.net/jira/browse/DTSSTCI-418
done
```
[ ] Yes
[x] No
```
=> DTSSTCI-418: Updated worktypes

src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn
https://tools.hmcts.net/jira/browse/DTSSTCI-417
Added
```
[ ] Yes
[x] No
```
=> DTSSTCI-417: Added judicial permission in DMN

src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn
https://tools.hmcts.net/jira/browse/DTSSTCI-442
updated
```
[ ] Yes
[x] No
```
=> DTSSTCI-442: Updated permission DMN for judges

src/main/resources/wa-task-cancellation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn
Jira Link:
https://tools.hmcts.net/jira/browse/DTSSTCI-423
Update the Cancellation tasks DMN to match the specifications in https://tools.hmcts.net/confluence/display/SPT/CIC+-+Service+Configuration#CICServiceConfiguration-4.1-DMNPreparationTable
=> [DTSSTCI-423] Update cancellation DMN to match spec.

src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn
https://tools.hmcts.net/jira/browse/DTSSTCI-428
updated
```
[ ] Yes
[x] No
```
=> DTSSTCI-428: Updated permissions DMN

src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn
https://tools.hmcts.net/jira/browse/DTSSTCI-444
Added dueDateOrigin
```
[ ] Yes
[x] No
```
=> DTSSTCI-444: Added dueDateOrigin to configuration DMN

src/main/resources/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/utils/CamundaTaskConstants.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/utils/CaseDataBuilder.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/utils/ConfigurationExpectationBuilder.java, src/test/resources/caseData/custom-case-data.json
https://tools.hmcts.net/jira/browse/DTSSTCI-671
completed
```
[ ] Yes
[x] No
```
=> DTSSTCI-671: Updated tests for task configuration DMN

src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/DTSSTCI-673
updated
```
[ ] Yes
[x] No
```
=> DTSSTCI-673: Updated tests for task permission DMN

src/main/resources/wa-task-cancellation-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaCancellationTest.java, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/utils/CancellationScenarioBuilder.java
https://tools.hmcts.net/jira/browse/DTSSTCI-669
completed
```
[ ] Yes
[x] No
```
=> DTSSTCI-669: Updated tests for task cancellation DMN

src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/DTSSTCI-672
completed
```
[ ] Yes
[x] No
```
=> DTSSTCI-672: Updated tests for task initiation DMN

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskCompletionTest.java
https://tools.hmcts.net/jira/browse/DTSSTCI-688
updated
```
[ ] Yes
[x] No
```
=> DTSSTCI-688: Updated completion event for ProcessFurtherEvidence task

src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/reform/wataskconfigurationtemplate/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/DTSSTCI-689
updated
```
[ ] Yes
[x] No
```
=> DTSSTCI-689: Updated initiation event for StitchCollateHearingBundle task

src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/st/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/DTSSTCI-709
updated with referral type and post event state
```
[ ] Yes
[x] No
```
=> DTSSTCI-709: Updated initiation DMN

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/st/taskconfiguration/dmn/CamundaTaskCompletionTest.java, src/test/java/uk/gov/hmcts/st/taskconfiguration/utils/CamundaTaskConstants.java
https://tools.hmcts.net/jira/browse/DTSSTCI-714
done
```
[ ] Yes
[x] No
```
=> DTSSTCI-714: Updated completion DMN

src/main/resources/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/st/taskconfiguration/dmn/CamundaTaskWaPermissionTest.java
https://tools.hmcts.net/jira/browse/DTSSTCI-715
updated
```
[ ] Yes
[x] No
```
=> DTSSTCI-715: Updated permission DMN

src/main/resources/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/st/taskconfiguration/dmn/CamundaTaskCompletionTest.java
https://tools.hmcts.net/jira/browse/DTSSTCI-716
updated
```
[ ] Yes
[x] No
```
=> DTSSTCI-716: Updated completion DMN

src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/st/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java, src/test/java/uk/gov/hmcts/st/taskconfiguration/utils/CamundaTaskConstants.java
https://tools.hmcts.net/jira/browse/DTSSTCI-854 
Update task initiation DMN with correct Process Categories 
```
[ ] Yes
[x] No
```
=> [DTSSTCI-854] Update task initiation DMN Process Category Identifiers

src/main/resources/wa-task-cancellation-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/st/taskconfiguration/dmn/CamundaTaskWaCancellationTest.java
https://tools.hmcts.net/jira/browse/DTSSTCI-855
Update Cancellation DMN and tests. 
```
[ ] Yes
[x] No
```
=> Dtsstci 855

src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/st/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/DTSSTCI-827
Update dmn for CompleteHearingOutcome task to be triggered by SystemTriggerCompleteHearingOutcome
**NOTE:** This is was built from DTSSTCI-749 to avoid conflicts: https://github.com/hmcts/st-wa-task-configuration/pull/156
```
[ ] Yes
[ ] No
```
=> DTSSTCI 827

src/main/resources/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/st/taskconfiguration/dmn/CamundaTaskWaInitiationTest.java
https://tools.hmcts.net/jira/browse/DTSSTCI-749
Update dmn for StitchCollateHearingBundle task to be triggered by SystemTriggerStitchCollateHearingBundle
```
[ ] Yes
[ ] No
```
=> DTSSTCI-749
